export const ROUTES = {
  HOMEPAGE: '/',
  PRODUCT: '/product',
  PRODUCT_DETAIL: (id: string) => `/product/${id}`,
  CART: '/cart',
  CHECKOUT: '/checkout',
  CHECKOUT_SHIPPING: '/checkout/shipping',
  CHECKOUT_PAYMENT: '/checkout/payment',
  PROFILE: '/my-account',
  PROFILE_ORDERS: '/profile/orders',
  PROFILE_SETTINGS: '/profile/settings',
  ABOUT: '/about',
  CONTACT: '/contact',
  LOGIN: '/login',
  REGISTER: '/register',
  FAQ: '/faq',
  TERMS: '/terms',
  PRIVACY: '/privacy',
  PRODUCT_CATEGORY: (slug: string) => `/category/${slug}`,
  HOME: '/',
  //Category
  CAT_GUCCI: '/gucci',
  CAT_VERSACE: '/versace',
  CAT_ZARA: '/zara',
  CAT_PRADA: '/prada',
  CAT_CALVINKLEIN: '/calvinklein',
};
